---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: langfuse-secret
  namespace: langfuse
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: langfuse-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: langfuse
        property: secret_key
    - secretKey: salt
      remoteRef:
        key: langfuse
        property: salt
    - secretKey: postgres_password
      remoteRef:
        key: langfuse
        property: postgres_password
