---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hf-token
  namespace: vllm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: hf-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: hf
        property: token
